### ISSUE TITLE
Create LND createwallet & unlock middleware

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-os#11]
Add in a docker container for use within the images for creating a wallet and unlocking the middleware for this.

For temporary development, store secrets on the filesystem (#5 ). But eventually we want to encrypt them in some way.

**Comment by mayankchhabra** [comment]
we do have middleware for it now https://github.com/getumbrel/umbrel-middleware/blob/af60c69f474d238b9a829f364325537d9f4c2c30/routes/v1/lnd/wallet.js#L81

**Comment by nolim1t** [comment]
Cool. We don't need this then
