### ISSUE TITLE
Support for RockPro64

### ISSUE THREAD

**Issue by thunderbiscuit** [getumbrel/umbrel-os#129]
Hey guys!

Absolutely love what you're building with Umbrel. I'm looking to get my own Umbrel node working with testnet on a RockPro64 from [PINE64](https://www.pine64.org/). I'm not super familiar with the differences between the OS needed for Raspberry Pis and RockPros, but I just wanted to let you know that I'd be down for helping with the testing if that's something you're looking at supporting in the future!

Let me know if you have time/ideas as to where to start for that. Should I just try the OS as-is and report back?

Cheers!

**Comment by AaronDewes** [comment]
I'm not sure what files are normally on the boot partition of a RockPro. Can you list them?

**Comment by nolim1t** [comment]
you should be able to run it on rockpro already, as its from pine64. I have no issues running this on pine64 hardware as I use a Pinebook already.

Simply use the https://github.com/getumbrel/umbrel project instead and follow the instructions from there.

As for a complete solution, you'd want to take a look at the [pmbootstrap](https://gitlab.com/postmarketOS/pmbootstrap) and [pmaports](https://gitlab.com/postmarketOS/pmaports) project

**Comment by thunderbiscuit** [comment]
Thanks guys!

@AaronDewes I'm not exactly sure what you mean. The files on the BIOS somehow? If instead you mean somewhere in the kernel or distro, the RockPro doesn't have an "official" OS like the Pi does. Not sure if that helps... let me know if I can help you further.

@nolim1t yeah totally I might just grab like the Manjaro ARM distro and do it using the instructions provided on the umbrel repo. But I also want to throw my support behind having the 1-click install that `umbrel-os` offers working on the RockPro if that's in the cards. The myNode project for example installs on a few different single board computers off the bat, which is a nice feature.

**Comment by nolim1t** [comment]
I think building an alpine apk (postmarket os) package might be a way too. Then can use pmbootstrap to install

**Comment by AaronDewes** [comment]
I've send you a DM on Telegram, I think I know how to get it to work.

**Comment by thunderbiscuit** [comment]
I managed to get all of this working; thanks to everyone who helped me out! [Blog post is here](https://thunderbiscuit.com/umbrel-rockpro/).

I think this issue is ready to be closed.

**Comment by mayankchhabra** [comment]
Great work, @thunderbiscuit! Thanks for penning down the blog post.

**Comment by fueleh** [comment]
Got this working on my pineA64 with @thunderbiscuit blog post thanks!
