### ISSUE TITLE
HDD failure. Can I recover?

### ISSUE THREAD

**Issue by BTCMachineElf** [getumbrel/umbrel-os#142]
Title pretty much says it all. I have a funded node w/funded channel and the HDD died. Deader than dead. I will replace it in a few days, but it seems the recovery functionality hasn't been rolled out yet. 

Can I recover? I have my channel backup.

There's only one channel, and I can get the remote node operator to force close it if need be. But if theres a way to recover, its preferable.

**Comment by BTCMachineElf** [comment]
There's only one channel, and I can get the remote node operator to force close it if need be. But if theres a way to recover its preferable.

**Comment by lukechilds** [comment]
Apologies for the delayed reply, yes, you can recover.

All you need is your seed phrase and you can recover from the Umbrel cloud backups. It's not implemented in the UI yet but we can talk you through the process.

**Comment by BTCMachineElf** [comment]
We've spoken on telegram, you'll sort me out there. Thanks!
