### ISSUE TITLE
Overclocking

### ISSUE THREAD

**Issue by AaronDewes** [getumbrel/umbrel-os#144]
The Raspberry Pi 400 runs at 1.8 GHz by default. How about doing the same overclocking on Umbrel OS by default? It might boost the initial bitcoin sync, and my RPi is running fine in a FLIRC case at 2.0 GHz, so it shouldn't be an issue. Also, with pi-gen it is possible to create two versions easily, one with and one without overclocking, so you could also provide both.

@mayankchhabra @lukechilds What do you think?

**Comment by lukechilds** [comment]
It's a cool idea but for Umbrel I think stability is more important than raw performance.

Whatever stock frequency the Pi comes at is what the Raspberry Pi Foundation have done extensive testing with and have decided is the most stable for most use cases.

Even if 2 Ghz works ok for some users, it may be less stable for others. Slower IBD but a more reliable device is optimal for Umbrel. We also don't know that all users have adequate cooling and it probably wouldn't be wise to expect all users to be knowledgable enough to know this themselves.

It could be interesting if we sold our own hardware at some point in the future so we could ensure we had adequate cooling and did extensive stability testing. However even then, I'd still say we should favour stability over perf. But we could do something interesting like overclock to 2 Ghz for IBD, then dynamically reduce clock speed to 1.5 Ghz for improved stability once IBD is complete.

However until we know we have adequate cooling on all devices and have done extensive stability testing, I'd be worried this could cause more problems than it solves. Gonna close this for now but thanks for the interesting idea!
