### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by spencerbeggs** [getumbrel/umbrel-os#179]
Communicating with the node over HTTP seems dicey. Would you be interested in a pull request that would generate SSL certs locally and then allow you to download the root cert from the settings menu? I might be able to hack that together.

**Comment by AaronDewes** [comment]
You're at the wrong repo, you should report the issue to [the main repo](https://github.com/getumbrel/umbrel)

**Comment by spencerbeggs** [comment]
Will do.
