### ISSUE TITLE
Kiosk Mode with Umbrel

### ISSUE THREAD

**Issue by jeffrey-l-turner** [getumbrel/umbrel-os#184]
I'm completely new to this project and working through the source code. Is there a simple way to run it in kiosk mode? I'd like to attach a touch screen interface to the Raspberry Pi and make it so I can interact with it like an appliance. Thank you for any thoughts/responses.

**Comment by AaronDewes** [comment]
I've already shared this on Telegram:
Step 1: Turn off the node
Step 2: Download Umbrel OS from https://github.com/UmbrelOS-Tweaks/desktop/releases/download/v0.3.2/umbrel-os-v0.3.2.zip
Step 3: Remove the SD card from the Pi and install the OS you downloaded there.
Step 4: Connect a monitor, press the (icon not displayed) start button in the top left corner, and open a Terminal.
Step 5: Run git clone https://github.com/UmbrelOS-Tweaks/umbrel-gui
Step 6: Run sudo apt-get -y install libqt5svg5-dev cmake make gcc g++ qtwebengine5-dev
Step 7: Run mkdir umbrel-gui/build && cd umbrel-gui/build && cmake .. && make -j4 && ./umbrel-gui

**Comment by jeffrey-l-turner** [comment]
Thank you
