### ISSUE TITLE
Remove wallet creation/unlock logic

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-os#19]
Wallet creation/unlocking, seed storage, etc is handled by https://github.com/getumbrel/umbrel-manager now

**Comment by nolim1t** [comment]
Wallet creation/unlock was never in the OS image to begin with. Auto unlock image can already be easily removed and is covered by other projects and also #18

**Comment by mayankchhabra** [comment]
AFAIU there are some helper scripts that do wallet creation, like the one below, which should be removed 
https://github.com/getumbrel/umbrel-os/blob/d0b08d9ef50e02f75c5806bfefc9050df45de5ae/stage2/04-docker-compose/files/umbrel-createwallet.py

**Comment by nolim1t** [comment]
Those aren't run at all,  but will fix this with #18
