### ISSUE TITLE
Upgrade OS to 64-bit

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-os#22]
Raspberry Pi OS (formerly Raspbian) 64-bit [has finally been released](https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370) in beta! We should use it as our base image.

**Comment by mayankchhabra** [comment]
Manually tested [umbrel-compose](https://github.com/getumbrel/umbrel-compose) on RPi 64-bit OS. Works great!!!

<img width="710" alt="Screen Shot 2020-06-02 at 6 12 04 PM" src="https://user-images.githubusercontent.com/10330103/83521468-e772dd80-a4fc-11ea-9914-6d794025bf35.png">

Waiting for pi-gen to [update their tool with 64-bit support](https://github.com/RPi-Distro/pi-gen/issues/413).

**Comment by nolim1t** [comment]
just need their source

**Comment by AaronDewes** [comment]
You can use this until they release their source code: https://github.com/RPi-Distro/pi-gen/pull/425

**Comment by mayankchhabra** [comment]
Thanks, @AaronDewes. What is the difference between this and the official RPi 64-bit OS?

**Comment by AaronDewes** [comment]
I don't know. I don't use the official Raspberry Pi OS, so I'm not sure what's different, but it should be mostly the same. This uses Debian as base (the official OS does the same), but all additional packages in Raspbian (except the ones which Raspberry Pi doesn't provide an ARM64 version yet).

**Comment by AaronDewes** [comment]
I could submit a PR here if you want. Do you want to only have ARM64 or both?

**Comment by mayankchhabra** [comment]
Thanks, @AaronDewes.

We'll test out your branch over the coming weeks to see if everything works OK and is compatible with our stack. Once everything is tested, we'll ditch the 32-bit OS completely as RPi 4 is our primary target device.

If you wanna help out with it, you're more than welcome!

**Comment by nolim1t** [comment]
I think arm64 only is fine

**Comment by AaronDewes** [comment]
They created their own ARM64 branch now.

**Comment by nolim1t** [comment]
awesome. Feel free to send a PR if you want. Would love to test it.

The current project maintainers are stretched thin against many things.

**Comment by AaronDewes** [comment]
I'll do that. Currently testing.

**Comment by nolim1t** [comment]
Cool thanks On Fri, Jul 3, 2020 at 16:54, Aaron Dewes <notifications@github.com> wrote:  
I'll do that. Currently testing.
