### ISSUE TITLE
Web interface didn't start on first boot

### ISSUE THREAD

**Issue by markshep** [getumbrel/umbrel-os#220]
I ssh'd in and ran the debug script which uploaded this: https://umbrel-paste.vercel.app/1cacc1c2db3b2f08fcab91cfc7779795

It looks like it formatted the SSD, but then umbrel-external-storage.service failed with a dependency issue :-(.

**Comment by AaronDewes** [comment]
It seems like your SSD (enclosure) uses too much power or you got a bad power supply.

**Comment by markshep** [comment]
I'm using the official Raspberry Pi power supply so it must be the SSD.  I used a Crucial one that I happened to have lying around, but it's an older M500 model rather than the MX500.  It says 1.7A on the back and looking at the [Raspberry Pi Power Supply page](https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md) it says the model 4B can only supports up to 1.2A for peripherals :-(.

Is there actually a bit in the logs somewhere which told you it was a power issue, or did you just know that from having dealt with these issues before?

![ssd-top](https://user-images.githubusercontent.com/490067/120334271-69503f00-c2e8-11eb-9e3f-64ec05ef7ffc.jpg)
![ssd-bottom](https://user-images.githubusercontent.com/490067/120334279-6c4b2f80-c2e8-11eb-99e4-501f3056d43c.jpg)

**Comment by AaronDewes** [comment]
> Is there actually a bit in the logs somewhere which told you it was a power issue, or did you just know that from having dealt with these issues before?

The logs told me the SSD didn't get connected properly, and having dealt with this issue probably 100s of times tells me that it's a power issue

**Comment by markshep** [comment]
Looking around at photos of the MX500 on the internet they also say 1.7A on the bottom, but I guess if you know they work then they must actually draw much less current in day to day usage, so I'll buy one of those.  Thanks for your help!

**Comment by AaronDewes** [comment]
> Looking around at photos of the MX500 on the internet they also say 1.7A on the bottom, but I guess if you know they work then they must actually draw much less current in day to day usage, so I'll buy one of those. Thanks for your help!

It often also depends on the SSD enclosure, not only the SSD itself

**Comment by markshep** [comment]
I used the recommended enclosure, so it was only the drive that was different.  I've now got an MX500 and installed it and everything is working now:

<img width="500" alt="dashboard" src="https://user-images.githubusercontent.com/490067/120707687-8fc1d600-c4b2-11eb-8081-4b9dab5b5cfd.png">
