### ISSUE TITLE
Install fail2ban

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-os#23]
Install fail2ban to prevent SSH brute-force attacks. The default configuration should be fine as it is.

**Comment by nolim1t** [comment]
Could be something for later. Right now theres not much reason for giving ssh access to the outside world when the dashboard does most things.

And anyone with ssh access will probably know what to do

**Comment by mayankchhabra** [comment]
Agree, but since SSH is enabled by default and users already have access to it, it's better to at least limit the number of password retries. 

OR, we can disable SSH by default, and the option to enable can be inside the dashboard. I like this approach better, your thoughts?

**Comment by nolim1t** [comment]
Will eventually disable all password access
