### ISSUE TITLE
Fresh install Kernel Panic on Raspi 4B 8gb

### ISSUE THREAD

**Issue by ghost** [getumbrel/umbrel-os#233]
Umbrel 4 fresh download nothing else connected - getting an issue with resize.sh error -117

**Comment by jeffersonn-1** [comment]
3.14 works fine for resizing the fs.

**Comment by byroncoetsee** [comment]
Can you provide details on the storage device? HDD/SSD? Was it formatted before and if so, to which fs type? Can it be read on another device (for example your laptop)?

**Comment by AaronDewes** [comment]
That error is related to the SD card, can you show the full error though?
