### ISSUE TITLE
Infinite loading after putting the password and hit Log in

### ISSUE THREAD

**Issue by tifDev** [getumbrel/umbrel-os#241]
![image](https://user-images.githubusercontent.com/39730484/135936924-eec15362-bb83-4f29-bd35-fff1b2e7c277.png)

After a unexpected shutdown, the node gets stuck in login, however I can login via SSH.

What can I do? Any troubleshooting?

Thanks.

**Comment by jonsyu** [comment]
Closed due to inactivity, let us know on https://community.getumbrel.com if the issue still exists - it would be helpful for us to see the debug logs if this is still happening, thanks!
