### ISSUE TITLE
Add ability to set : Tor Bridge / WireGuard / OpenVPN from umbrel dashboard

### ISSUE THREAD

**Issue by mehdiirh** [getumbrel/umbrel-os#243]
Hi. I just started to implement my node few days ago.
And had a lot of problem with umbrel, the biggest problem was umbrel did not start downloading blockchain and it was stuck on 0 Peers, after 3 days messing around with logs and the OS, I found out unfortunately tor is blocked in my country, so umbrel can't work as expected ! 
I tried to add bridge to the tor `/etc/tor/torrc` but seems it doesn't affect umbrel, as It runs tor with docker, I don't know where is `torrc `of umbrel and where I should put my bridge configurations so umbrel can use them.

In my opinion umbrel should add this feature in next release, so anybody can simply set their bridge config using the dashboard.
I would be proud if I could open a pull request but unfortunately I'm not familiar with bash. Please let me know if you will do that. Thank you in advance

**Comment by jonsyu** [comment]
Hey, I'm closing this just because Tor bridges have been brought up a few times - the main issue is that tor bridges require a static IP for your pi to work, so we're investigating options.

**Comment by brunoAmado** [comment]
ip fixes ? Can we use duckDNS.org to help?!
