### ISSUE TITLE
Containerize Tor

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-os#25]
Currently, Tor is installed on the system. We should containerize it and run it as a docker service as a part of https://github.com/getumbrel/umbrel-compose

**Comment by nolim1t** [comment]
this needs to wait till we have a working version of lnd 0.10.0

**Comment by nolim1t** [comment]
However I'll put necessary infrastructure in place to allow for this in due time

**Comment by nolim1t** [comment]
a lot of the work is related to https://github.com/getumbrel/umbrel-os/issues/9

**Comment by nolim1t** [comment]
I will close this because this is a duplicate.

It will happen eventually to keep things cleaner
