### ISSUE TITLE
Missing documentation for backup logic. 

### ISSUE THREAD

**Issue by ybaidiuk** [getumbrel/umbrel-os#277]
if i get ssd error can i recover my channels or i can only force close it? 
It will recover my channel or just force close it ? 
is my last balance is wrong because umbel do not update my channel state for each routing, and i force closing channel i can potentially lose all fund ?

**Comment by usernameisJim** [comment]
If something happens all you need is your 24 words with automated recovery demonstrated below, it will close channels and recover all funds onchain on a new instance: 

https://twitter.com/umbrel/status/1562099972547690501

I recommend this as the safest and most reliable option, as opposed to offchain channel migration as per LND documentation a lot can go wrong there and it's good to test it out first
