### ISSUE TITLE
Log to RAM to prevent SD degradation

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-os#30]
Not necessarily required right now, but definitely worth considering in the near future. https://github.com/azlux/log2ram

**Comment by nolim1t** [comment]
good idea

**Comment by mayankchhabra** [comment]
This a good thread for more ideas - https://www.thethingsnetwork.org/forum/t/how-can-microsd-flash-memory-wear-be-minimized/15896

**Comment by nolim1t** [comment]
Will look at this after partitioner / swap

**Comment by nolim1t** [comment]
Testing this out too

**Comment by nolim1t** [comment]
Can't get it to work? Anyone else?

**Comment by mayankchhabra** [comment]
What's the issue you're facing?

**Comment by nolim1t** [comment]
doesnt run at all

**Comment by nolim1t** [comment]
I'm more for making the SD card a read only filesystem, and putting everything (including moving docker images) onto the external media. SD card is a lot harder to replace

**Comment by mayankchhabra** [comment]
If you've got it working like that, then sure let's try it. But if it's too much work, then just logging to RAM will save the SD from a ton of unnecessary hammering.

**Comment by nolim1t** [comment]
probably be something as part of creating a partition.. stop docker, then move all the docker stuff over, and then start docker again.  Then make everything read only.

**Comment by mayankchhabra** [comment]
Hmm feel free to give it shot if you want to. IMO we can stick with just offloading the logs to SD Card for the public beta, and create a RO filesystem on SD post that.

**Comment by nolim1t** [comment]
Yes this is a nice to have..

**Comment by mayankchhabra** [comment]
Replaced by https://github.com/getumbrel/umbrel/issues/206
