### ISSUE TITLE
Bundle Umbrel Compose's Docker Images

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-os#32]
### Issue
Even though Umbrel OS ships pre-bundled with [Umbrel Compose](https://github.com/getumbrel/umbrel-compose), it has to pull all the docker images of services defined in `$HOME/docker-compose.yml` from docker hub on the first-boot. This adds a significant delay in the initial setup, thus having the user wait indefinitely to access the dashboard at http://umbrel.local without any method of keeping them updated with progress, ETA, or status of what's going on.

Also, the first image pulls are always the longest as there are no cached intermediary images, plus as we add more services to Umbrel Compose, it will only increase the delay.

### Solution
Add a step in stage 2 of image generation which pulls and bundles all the docker images of services defined in `$HOME/docker-compose.yml`. Now since no image pulls will be required on the first boot, the user would be able to instantly access their dashboard at http://umbrel.local.

Also, there is no benefit of pulling images on the first boot as we're not pulling the latest images anyway (since they are pulled in accordance with their version tags defined in `$HOME/docker-compose.yml`) so bundling them does no harm.

**Comment by nolim1t** [comment]
yeah its a good one. But also a tough one to solve

**Comment by mayankchhabra** [comment]
If we just add a new step to [stage 2](https://github.com/getumbrel/umbrel-os/tree/master/stage2) called `10-pull-images` and do `docker-compose pull` inside it, would that not be enough?

**Comment by nolim1t** [comment]
Maybe possible

**Comment by nolim1t** [comment]
If you know how to solve the following let me know.

![docker-compose pull error](https://user-images.githubusercontent.com/83470/83747542-fb4c4a00-a68a-11ea-9126-9282cd1528fb.png)

**Comment by nolim1t** [comment]
sounds plausible but I'll wait till the partitioning stuff is fully merged before I take this on to minimize potential conflicts
