### ISSUE TITLE
Add CLI Hardware wallet support

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-os#37]
Add CLI Hardware wallet support so we can eventually support HW wallets and users do not have to keep their funds on the node.

Initially just allow CLI access so we can debug.

Would eventually lead to an increase of the value proposition of having the node, rather than doing using a hot wallet.

## Reference material

* [Python HWI interface](https://github.com/bitcoin-core/HWI)
* [Creating a HW wallet](https://gist.github.com/achow101/a9cf757d45df56753fae9d65db4d6e1d)

**Comment by mayankchhabra** [comment]
Great idea! Moving this to medium/long-term idea board.
