### ISSUE TITLE
Remove Tor

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-os#38]
Now that Tor is dockerized, we can remove it from the OS after https://github.com/getumbrel/umbrel-compose/pull/28 is merged

**Comment by nolim1t** [comment]
No its not possible. We still need it to generate passwords. Maybe after the passwords has been generated it can

**Comment by mayankchhabra** [comment]
We can use containerized Tor to generate hashed password. Already fixed here: 
https://github.com/getumbrel/umbrel-compose/blob/a7e6614d4dfe81bc582d04a35f4c2a39f8e9b2f3/configure-box.sh#L78

**Comment by nolim1t** [comment]
ok i saw that one

**Comment by mayankchhabra** [comment]
Closed by #44
