### ISSUE TITLE
Curl doesn't work

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-os#45]
Curl doesn't work out-of-the-box with many https URLs (including GitHub). 

![image](https://user-images.githubusercontent.com/10330103/86732397-014c9680-c04e-11ea-9400-b14247d5cbca.png)

We need to add `CURL_CA_BUNDLE` globally for it to work.

```
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
```

**Comment by nolim1t** [comment]
yes use wget

**Comment by mayankchhabra** [comment]
Yep, but many installation scripts that we don't write could be using `curl`. No harm in just exporting `CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`

**Comment by mayankchhabra** [comment]
Just adding it to `/etc/profile` should work

**Comment by mayankchhabra** [comment]
Automagically fixed by #43 🎉
