### ISSUE TITLE
Generate custom torrc config with tor secrets

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-os#9]
Use the following
```tor --hash-password <password>```

But we might need to have a default for storing secrets. Maybe use the LND unlock password to do this right now?

**Comment by mayankchhabra** [comment]
Let's use the dashboard's password (which is also lnd's password) (hashed and stored in `$HOME/db/user.json`) for this too! Consistency FTW!

**Comment by nolim1t** [comment]
the only issue is this has to be generated before any user logs in.

**Comment by nolim1t** [comment]
Im not going to bother with encrypting them.. they will never be exposed externally and the impact is extremely low. because they are not encrypted in the config files anyway

**Comment by nolim1t** [comment]
Once https://github.com/getumbrel/umbrel-compose/pull/28 is released will add in the changes into rc.local or have it run configure-box.sh on first run

**Comment by mayankchhabra** [comment]
Fixed.
